### ISSUE TITLE
Containers running but I can't access to the app via web browser.

### ISSUE THREAD

**Issue by titooo7** [antebrl/IPTV-Restream#30]
OS: Ubuntu 22.04 where I have sonarr, plex and other apps installed via [saltbox](https://[docs.saltbox.dev](https://docs.saltbox.dev/)/) which uses traefik to load every app with an url like appname.mydomain.com

**Steps:**
"git clone https://github.com/antebrl/IPTV-Restream.git" and then "docker compose up -d"
I get this error:
_Error response from daemon: driver failed programming external connectivity on endpoint iptv-restream-nginx-1 (5c70f8fc2f66d01eba851d5e5c1e45a0b558c988ef40fce0c315851d5e4ed6b4): Bind for 0.0.0.0:80 failed: port is already allocated_

**How I fixed above error:**
I changed changing the port to 8080:8080 in the docker-compsoe.yml file, then I made "docker compose up -d"
Now iptv-restream-backend-1, iptv-restream-frontend-1, iptv-restream-nginx-1 are running but none of the following sites I tried is loading:

**Current issue**
Nothing loads at http://mydomain.com:8080, http://mydomain.com:5000, http://my-server-ip-address:8080, http://my-server-ip-address:5000 

I tried adding my domain and also my server IP address to the yml file on the VITE_BACKEND_URL line, but it didn't make a difference.

Not sure if the fact that this solution doesn't use traefik is what doesn't allow me to access to it despite the containers are running

**Comment by antebrl** [comment]
Change the port mapping of the nginx-container in the docker-compose.yml to `8080:80`, as the second port is the container internal port and nginx listens on port 80. The application should then be accessible on http://mydomain.com:8080
If that won't fix it, we have to look into the traefik configuration.
